# Generated by Django 4.2.7 on 2025-09-08 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={},
        ),
        migrations.AlterModelOptions(
            name='careerrecommendation',
            options={'ordering': ['rank']},
        ),
        migrations.AlterModelOptions(
            name='studentassessment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.RenameField(
            model_name='careerrecommendation',
            old_name='custom_career_name',
            new_name='career_name',
        ),
        migrations.AlterUniqueTogether(
            name='careerrecommendation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='career',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='career',
            name='skills_required',
        ),
        migrations.RemoveField(
            model_name='studentassessment',
            name='extracurricular_activities',
        ),
        migrations.RemoveField(
            model_name='studentassessment',
            name='future_goals',
        ),
        migrations.RemoveField(
            model_name='studentassessment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AddField(
            model_name='careerrecommendation',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='careerrecommendation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='career',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='career',
            name='growth_prospects',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AlterField(
            model_name='career',
            name='min_score_threshold',
            field=models.FloatField(default=60.0),
        ),
        migrations.AlterField(
            model_name='career',
            name='salary_range',
            field=models.CharField(default='Competitive', max_length=100),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='confidence_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='reasoning',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='career_interests',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='education_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='personality_traits',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='session_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='subject_scores',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='match_percentage',
        ),
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='rules_applied',
        ),
    ]
