# Generated by Django 4.2.7 on 2025-09-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0002_alter_career_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='career_name',
        ),
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='description',
        ),
    ]
