# Generated by Django 4.2.7 on 2025-10-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0003_remove_careerrecommendation_career_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='counselor.studentassessment'),
        ),
        migrations.AlterUniqueTogether(
            name='careerrecommendation',
            unique_together={('assessment', 'career')},
        ),
    ]
